### ISSUE TITLE
I made a doc with proxies like 2 years ago, if you want I can turn ownership over to you

### ISSUE THREAD

**Issue by dinguschan-owo** [aztro-leakz/BYPAZZR#3]
If you want ownership u can have it, or you can just strip it for links :D

https://docs.google.com/document/d/1mld6TbHaNrY8vcALdbFagsM5PE4HHgp_oNNrevlLYjg/edit?usp=sharing

**Comment by aztro-leakz** [comment]
thank you so much

**Comment by aztro-leakz** [comment]
@dinguschan-owo how did you make the Google doc look like that? I'm trying to improve the way mine looks

**Comment by dinguschan-owo** [comment]
@aztro-leakz lmao I just clicked make drawings and used the shapes. I could maybe help you if u can't figure it out

**Comment by aztro-leakz** [comment]
okey thx

**Comment by aztro-leakz** [comment]
I hate securly sm

**Comment by aztro-leakz** [comment]
also @dinguschan-owo does dingus proxy not worky??? it looks sick asf

**Comment by dinguschan-owo** [comment]
dingusProxy works, but I'm tryna deprecate it cause it's less good than Helios, and it's kinda ugly ngl

**Comment by aztro-leakz** [comment]
oh I see. when I try to search sumth on it it never pops up so that's why I asked if it still worked
